import image1 from "../assets/Magdiel Lopez 15.png";
import image2 from "../assets/Magdiel Lopez 17.png";
import image3 from "../assets/download (1).jfif";

export interface nft_detail{
    heading:string,
    body:string
    image:string
    className: string;

}
export const nft_details:nft_detail[] =[
    {
        heading:'Thousands of unique NFTs',
        body:'Each character is entirely unique and is generated by combing attributes such as colour palattes, skin tones, facial traits, outfits and accessories.with nearrly endly combination, all characters are guaranteed to be one of a kind.',
        image:image1,
        className:'first_card'
    },
    {
        heading:'Secure the most rare',
        body:'Even though the two Tinyfaces will ever be the same. some variations are rarer than the others. watch out for special accessories and raw materials - the rarer the attributes. tthe rarer your character will be.',
        image:image2,
        className:'second_card'
    },
    {
        heading:'Our environmental is cheap',
        body:'in order to enable our community to spend a little as possible in gas fees when minting, we opted for a contract make by Azuki called ERC721A. which allows minting multiple NFTs for essentially the same cost as minting a single one',
        image:image3,
        className:'third_card row__flex__card'

       

    },
]