import Card from "./Card";
import image1 from "../assets/Magdiel Lopez 15.png";
import image2 from "../assets/Magdiel Lopez 17.png";
import image3 from "../assets/download (1).jfif";

const Nft_details = () => {
  return (
    <section className="nft__details__section">
      <div className="container nft__details__container">
        <Card
          body="Each character is entirely unique and is generated by combing
          attributes such as colour palattes, skin tones, facial traits, outfits
          and accessories.with nearrly endly combination, all characters are
          guaranteed to be one of a kind."
          className="first_card"
          heading="Thousands of unique NFTs"
          image={image1}
        />
        <Card
          body="Each character is entirely unique and is generated by combing
          attributes such as colour palattes, skin tones, facial traits, outfits
          and accessories.with nearrly endly combination, all characters are
          guaranteed to be one of a kind."
          className="second_card"
          heading="Thousands of unique NFTs"
          image={image2}
        />
        <Card
          body="Each character is entirely unique and is generated by combing
          attributes such as colour palattes, skin tones, facial traits, outfits
          and accessories.with nearrly endly combination, all characters are
          guaranteed to be one of a kind."
          className="third_card row__flex__card"
          heading="Thousands of unique NFTs"
          image={image3}
        />
      </div>
    </section>
  );
};

export default Nft_details;
